package.name = 'client'
package.version = '0.0.0'
package.description = 'A Tauri App'
package.authors = ['you']
package.license = ''
package.repository = ''
package.edition = '2021'
package.rust-version = '1.57'
build-dependencies.tauri-build.version = '2.0.0-alpha.8'
build-dependencies.tauri-build.features = []
dependencies.serde_json = '1.0'
dependencies.serde.version = '1.0'
dependencies.serde.features = ['derive']
dependencies.tauri.version = '2.0.0-alpha.12'
dependencies.tauri.features = []
features.default = ['custom-protocol']
features.custom-protocol = ['tauri/custom-protocol']
lib.crate-type = ['staticlib', 'cdylib', 'rlib']
